In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pickle

FILENAME = 'c1p8_3.4.pickle'

with open(FILENAME, 'rb') as f:
    data = pickle.load(f)
    
    

In [3]:
data


{'stim': array([-111.94824219,  -81.80664062,   10.21972656, ...,    9.78515625,
          24.11132812,   50.25390625]),
 'rho': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)}

In [4]:
1/500


0.002

In [5]:
300/2


150.0

In [8]:
data['rho'].count(1)

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [9]:
import collections
collections.Counter(data['rho'])

Counter({0: 546399, 1: 53601})

In [10]:
data['rho'].size()

TypeError: 'int' object is not callable

In [15]:
np.count_nonzero(data['rho'] == 1)

53601

In [16]:
np.nonzero(data['rho'] == 1)

(array([    17,     22,     25, ..., 599936, 599941, 599947]),)

In [17]:
test = data['rho'][:26]
test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1], dtype=uint8)

In [18]:
np.where

<function numpy.core.multiarray.where>

In [19]:
np.where?

In [22]:
np.where((np.nonzero(data['rho'] == 1) & (np.nonzero(data['rho'] == 1) > 150)))

TypeError: '>' not supported between instances of 'tuple' and 'int'

In [23]:
clear

In [24]:
import numpy as np
import pickle

FILENAME = 'c1p8_3.4.pickle'

with open(FILENAME, 'rb') as f:
    data = pickle.load(f)

In [25]:
stim = data['stim']
rho = data['rho']

In [26]:
rho


array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [27]:
rho.size

600000

In [28]:
stim.size

600000

In [29]:
stim

array([-111.94824219,  -81.80664062,   10.21972656, ...,    9.78515625,
         24.11132812,   50.25390625])

In [30]:
np.count_nonzero(rho == 1)

53601

In [50]:
np.nonzero(rho == 1)[0]

array([    17,     22,     25, ..., 599936, 599941, 599947])

In [53]:
spikes_index = np.nonzero(rho == 1)[0]
spikes_index

array([    17,     22,     25, ..., 599936, 599941, 599947])

In [54]:
np.count_nonzero(spikes_index)

53601

In [55]:
np.prod(spikes_index.shape)

53601

In [60]:
validSpikes_index = np.where(spikes_index > 150)[0]
validSpikes_index

array([   18,    19,    20, ..., 53598, 53599, 53600])

In [61]:
validSpikes_index.size

53583

In [62]:
53601-53583

18

In [63]:
cut = spikes_index[:20]

In [64]:
cut

array([ 17,  22,  25,  31,  34,  39,  44,  48,  50,  56,  61,  66,  71,
        81, 102, 109, 117, 126, 158, 160])

In [65]:
num_timesteps = 150
sta = np.zeros((num_timesteps,))



In [72]:
sta

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:

spike_times = rho[num_timesteps:].nonzero()[0] + num_timesteps



In [68]:
spike_times

array([   158,    160,    162, ..., 599936, 599941, 599947])

In [69]:
np.count_nonzero(spike_times)

53583

In [70]:
stim

array([-111.94824219,  -81.80664062,   10.21972656, ...,    9.78515625,
         24.11132812,   50.25390625])

In [73]:
2*600000


1200000

In [74]:
1200000/1000.


1200.0

In [75]:
np.nonzero(rho == 1)

(array([    17,     22,     25, ..., 599936, 599941, 599947]),)

In [76]:
np.nonzero(rho == 1)[0]

array([    17,     22,     25, ..., 599936, 599941, 599947])

In [77]:
np.nonzero(rho == 1)[0].size

53601

In [78]:
stim

array([-111.94824219,  -81.80664062,   10.21972656, ...,    9.78515625,
         24.11132812,   50.25390625])

In [80]:
stim[0:2]

array([-111.94824219,  -81.80664062])

In [84]:
stim[spike_times[0]-150:spike_times[0]].size

150

In [87]:
num_spikes = 53583
stmatrix = np.zeros((num_timesteps,num_spikes))
stmatrix


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [88]:
stmatrix[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [91]:
    for i in range(0,num_spikes):
        for j in range(0,150):
            stmatrix[i][j] = stim[spike_times[j]-150:spike_times[j]]

ValueError: could not broadcast input array from shape (150) into shape (53583)

In [93]:
    stmatrix = np.zeros((num_timesteps,num_spikes))
    for i in range(0,num_spikes):
        stmatrix[i] = stim[spike_times[i]-150:spike_times[i]]

ValueError: could not broadcast input array from shape (150) into shape (53583)

In [102]:
    num_spikes = 53583
    num_timesteps = 150
    stmatrix = np.zeros((num_spikes,num_timesteps))
    j = 0

    for i in range(0,num_spikes):
        stmatrix[i] = stim[spike_times[j]-150:spike_times[j]]
        j += 1
        

In [103]:
stmatrix

array([[-2.72949219e+01, -2.02441406e+01, -3.22167969e+01, ...,
         1.23779297e+01, -8.88671875e+00, -1.51123047e+01],
       [-3.22167969e+01, -8.61816406e+00,  3.50634766e+01, ...,
        -1.51123047e+01, -2.32421875e+00,  6.96777344e+00],
       [ 3.50634766e+01,  5.59228516e+01,  4.67285156e+01, ...,
         6.96777344e+00,  1.50390625e+00, -4.41943359e+01],
       ...,
       [ 6.04687500e+01,  7.70019531e+01,  7.52050781e+01, ...,
        -9.60937500e+00, -1.51660156e+01,  1.72802734e+01],
       [ 1.17968750e+01,  2.31835938e+01, -9.24804688e+00, ...,
        -3.42187500e+01, -7.33349609e+01, -5.86621094e+01],
       [ 1.36914062e+01,  3.41796875e-02,  3.56445312e+01, ...,
         1.14550781e+01,  4.78857422e+01,  5.16162109e+01]])

In [105]:
stmatrix.shape

(53583, 150)

In [106]:
type(stmatrix)

numpy.ndarray

In [109]:
a = stmatrix.mean(0)

In [110]:
a.shape

(150,)